site_name: Wiki
site_description: Perspectives on Neuroscience, Mathematics, and Machine Learning
site_author: Kaiwen Bian
site_url: https://kbian.org/Kaiwen-Wiki/
repo_url: https://github.com/KevinBian107/Kaiwen-Wiki

theme:
  name: material
  # custom_dir: docs/overrides
  # logo: assets/index/searching.png
  favicon: assets/index/logo.png
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for dark mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


  features:
    - navigation.sections
    # - toc.integrate
    - toc.follow
    # Tabs
    - navigation.tabs
    - navigation.tabs.sticky  # stays visible at the top
    - navigation.top
    - navigation.expand
    - navigation.prune
    - navigation.indexes 
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    # Insiders:
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.instant.preview
    - content.code.select
    - content.footnote.tooltips

plugins:
  - search
  # - privacy  # Caching dynamic badges
  - mkdocs-jupyter
  - mike
  # - autorefs
  # - gen-files:
      # scripts:
        # - scripts/gen_ref_pages.py
        # - scripts/gen_changelog.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  # - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            summary: true
            show_root_heading: true
            docstring_options:
              returns_multiple_items: false
            docstring_section_style: table  # table, list, spacy
  


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

  analytics:
    provider: google
    property: G-V7MWLE7LXW

  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/KevinBian107

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js
  - https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - js/main.js

extra_css:
  - css/custom.css

copyright: >
  Copyright &copy; 2024 Kaiwen Bian –
  <a href="#__consent">Change cookie settings</a>

nav:
  - My Wiki: index.md
  - Notes:
    # - Literature: literature/literatures.md
    - Notes: literature/notes.md
  - Neuroscience Related:
    - Cognitive Neuroscience's Perspective: articles/neuroscience/cognitive_brain.md
    - Sensory, Processing, and Affective Neuroscience: articles/neuroscience/affective_neuroscience.md
    - Searching & Parralel Processing: articles/neuroscience/parralel_reinforcing.md
    - Neural Adaptation With Cost: articles/neuroscience/systematic_deviation.md
    - What We Think Deternmines What We Can Think: articles/neuroscience/dev_neurobio.md
    - What You Think May Not Be What You Think: articles/neuroscience/out_of_helplessness.md
  - Mathamatics Related:
    - Twitch on Convex Optimization Theory: articles/mathamatics/optimization.md
    - All You Need Is Constraint Solving: articles/mathamatics/constraint.md
    - BuildingEverything From Sets: articles/mathamatics/point_set_topology.md
    - Unfolding Stochasticity Sequentially: articles/mathamatics/stochastic.md
    - Lend It Some Confidence: articles/mathamatics/confidence.md

